# Use Python image
FROM python:3.9-slim

# Set working directory inside the scraper project folder
WORKDIR /scraper

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the project files into the container
COPY . .

# Default command to keep the container running
# CMD ["bash"]

# Run the crawler when the container launches.
CMD [ "python3", "./go-spider.py" ]


# Dockerfile.dev